### ISSUE TITLE
GIBBON?

### ISSUE THREAD

**Issue by apjanke** [mikecroucher/awesome-MATLAB#36]
Hey, are you still maintaining this list?

What do you think about adding @Kevin-Mattheus-Moerman's GIBBON – https://www.gibboncode.org/? Seems like an ambitious enough project to be worthy of mention here.

**Comment by wspr** [comment]
Also see https://github.com/mattools, which are probably all worth adding! (I've used matgeom a little and it's worth a link)

**Comment by wspr** [comment]
(I presume we should write pull requests instead of asking Mike to add these for us?)

**Comment by apjanke** [comment]
> (I presume we should write pull requests instead of asking Mike to add these for us?)

I'm not going to presume to know where in the list/categories he wants them to know, or what descriptive text to put with them, so no PR from me. Hopefully a feature request is adequate.

**Comment by mikecroucher** [comment]
Feature requests are welcomed so are PRs :)
Someone has added Gibbon.

I am fairly chilled out about this list. If the PR looks sensible, I'll probably merge it.
