### ISSUE TITLE
Including Manopt in the list

### ISSUE THREAD

**Issue by bamdevm** [mikecroucher/awesome-MATLAB#39]
Hello Mike, 

Nicolas (https://github.com/NicolasBoumal) and I develop the Manopt toolbox [1, 2], which focuses on making manifold optimization more mainstream. It has a good (probably, the largest) collection of manifolds and solvers. We also have an active forum for discussion. 

We consider the Manopt toolbox as an awesome toolbox and hence, it would be great if you could add it to your awesome list awesome-MATLAB toolboxes. 😊

Regards,
Bamdev

[1] https://github.com/NicolasBoumal/manopt
[2] https://manopt.org

**Comment by mikecroucher** [comment]
HI Bamdev

Looks great. Feel free to make a pull request.

Cheers,
Mike

**Comment by mikecroucher** [comment]
Added. Sorry for the delay :)
